#!/bin/bash

# 新しいディレクトリを作成して移動
mkdir -p treasure_hunting
cd treasure_hunting || exit 1

# 作成するディレクトリのリスト
DIRECTORIES=(
    north
    south
    east
    west
    somewhere
    future
    past
    yesterday
    tomorrow
    today
    ncu
    nagoya
)

# 各ディレクトリを作成
for dir in "${DIRECTORIES[@]}"; do
    mkdir -p "$dir"
done

# ファイルをダウンロード
treasuredir="https://www.ds.nagoya-cu.ac.jp/~nose/class/keisoku"
wget -P "./ncu/"       $treasuredir"/01.txt"
wget -P "./north/"     $treasuredir"/02.txt"
wget -P "./yesterday/" $treasuredir"/03.txt"
wget -P "./nagoya/"    $treasuredir"/04.txt"
wget -P "./past/"      $treasuredir"/05.txt"
wget -P "./somewhere/" $treasuredir"/06.txt"
wget -P "./future/"    $treasuredir"/07.txt"
wget -P "./west/"      $treasuredir"/08.txt"
wget -P "./today/"     $treasuredir"/09.txt"
